"""add language to posts

Revision ID: 45155b102a29
Revises: e46170b4d0af
Create Date: 2020-06-18 21:30:45.931969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45155b102a29'
down_revision = 'e46170b4d0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
